"""add table args

Revision ID: 706ff142ae05
Revises: 7ea210f0e184
Create Date: 2023-04-24 14:10:08.548458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706ff142ae05'
down_revision = '7ea210f0e184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_phone_key', 'contact', type_='unique')
    op.drop_index('ix_contact_email', table_name='contact')
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.create_unique_constraint('unique_contact_phone_email_user', 'contact', ['phone', 'email', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_contact_phone_email_user', 'contact', type_='unique')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.create_index('ix_contact_email', 'contact', ['email'], unique=False)
    op.create_unique_constraint('contact_phone_key', 'contact', ['phone'])
    # ### end Alembic commands ###
